/* Auto-generated by json2lvgl.py — DO NOT EDIT */
#ifndef GATEWAYHMI_H
#define GATEWAYHMI_H

#include "lvgl/lvgl.h"

/* Screen creation */
lv_obj_t *ui_screen_create(void);

/* State control */
void ui_apply_state(const char *state_name);
void ui_toggle_state(const char *state_a, const char *state_b);

/* Widget accessors */
extern lv_obj_t *ui_wifi_ring;
extern lv_obj_t *ui_ble_ring;
extern lv_obj_t *ui_center_icon;
extern lv_obj_t *ui_data_panel_wifi;
extern lv_obj_t *ui_label_wifi;
extern lv_obj_t *ui_val_wifi;
extern lv_obj_t *ui_data_panel_ble;
extern lv_obj_t *ui_label_ble;
extern lv_obj_t *ui_val_ble;
extern lv_obj_t *ui_trigger_btn;

#endif /* GATEWAYHMI_H */