/*
 * GatewayHMI.c — Auto-generated by json2lvgl.py
 * Version: 1.0
 * Target: IT9866/IT9868 with IT2D GPU acceleration
 * DO NOT EDIT BY HAND — modify the JSON source instead.
 */

#include "lvgl/lvgl.h"
#include "ite_it2d.h"
#include "lv_draw_ite_it2d.h"
#include <string.h>
#include "GatewayHMI.h"

/* ══════════════════════════════════════════════════════ */
/* Screen: main_dashboard                                    */
/* ══════════════════════════════════════════════════════ */

lv_obj_t *ui_screen_create(void) {
    lv_obj_t *screen = lv_obj_create(NULL);
    lv_obj_set_size(screen, 480, 480);
    lv_obj_set_style_bg_color(screen, lv_color_hex(0x050A10), LV_STATE_DEFAULT);
    LV_IMG_DECLARE(img_bg_main_dashboard);
    lv_obj_set_style_bg_img_src(screen, &img_bg_main_dashboard, LV_STATE_DEFAULT);
    
    /* --- Widget: wifi_ring (image) --- */
    ui_wifi_ring = lv_img_create(screen);
    lv_obj_set_pos(ui_wifi_ring, 24, 24);
    lv_obj_set_size(ui_wifi_ring, 432, 432);
    LV_IMG_DECLARE(img_wifi_ring);
    lv_img_set_src(ui_wifi_ring, &img_wifi_ring);
    /* IT2D composite: layer=1, blend=additive */
    lv_obj_set_style_blend_mode(ui_wifi_ring, LV_BLEND_MODE_NORMAL, LV_STATE_DEFAULT);
    /* Animations for wifi_ring */
    static lv_anim_t anim_wifi_ring_0;
    lv_anim_init(&anim_wifi_ring_0);
    lv_anim_set_var(&anim_wifi_ring_0, ui_wifi_ring);
    lv_anim_set_exec_cb(&anim_wifi_ring_0, (lv_anim_exec_xcb_t)lv_img_set_angle);
    lv_anim_set_values(&anim_wifi_ring_0, 0, 3600);
    lv_anim_set_time(&anim_wifi_ring_0, 40000);
    lv_anim_set_delay(&anim_wifi_ring_0, 0);
    lv_anim_set_playback_time(&anim_wifi_ring_0, 40000);
    lv_anim_set_repeat_count(&anim_wifi_ring_0, 0);
    lv_anim_set_path_cb(&anim_wifi_ring_0, LV_ANIM_EASE_LINEAR);
    lv_anim_start(&anim_wifi_ring_0);
    
    /* --- Widget: ble_ring (image) --- */
    ui_ble_ring = lv_img_create(screen);
    lv_obj_set_pos(ui_ble_ring, 72, 72);
    lv_obj_set_size(ui_ble_ring, 336, 336);
    LV_IMG_DECLARE(img_ble_ring);
    lv_img_set_src(ui_ble_ring, &img_ble_ring);
    /* IT2D composite: layer=2, blend=additive */
    lv_obj_set_style_blend_mode(ui_ble_ring, LV_BLEND_MODE_NORMAL, LV_STATE_DEFAULT);
    /* Animations for ble_ring */
    static lv_anim_t anim_ble_ring_0;
    lv_anim_init(&anim_ble_ring_0);
    lv_anim_set_var(&anim_ble_ring_0, ui_ble_ring);
    lv_anim_set_exec_cb(&anim_ble_ring_0, (lv_anim_exec_xcb_t)lv_img_set_angle);
    lv_anim_set_values(&anim_ble_ring_0, 3600, 0);
    lv_anim_set_time(&anim_ble_ring_0, 30000);
    lv_anim_set_delay(&anim_ble_ring_0, 0);
    lv_anim_set_playback_time(&anim_ble_ring_0, 30000);
    lv_anim_set_repeat_count(&anim_ble_ring_0, 0);
    lv_anim_set_path_cb(&anim_ble_ring_0, LV_ANIM_EASE_LINEAR);
    lv_anim_start(&anim_ble_ring_0);
    
    /* --- Widget: center_icon (image) --- */
    ui_center_icon = lv_img_create(screen);
    lv_obj_set_pos(ui_center_icon, 180, 180);
    lv_obj_set_size(ui_center_icon, 120, 120);
    LV_IMG_DECLARE(img_center_icon);
    lv_img_set_src(ui_center_icon, &img_center_icon);
    LV_IMG_DECLARE(img_center_icon_error);
    
    /* --- Widget: data_panel_wifi (panel) --- */
    ui_data_panel_wifi = lv_obj_create(screen);
    lv_obj_set_pos(ui_data_panel_wifi, 30, 348);
    lv_obj_set_size(ui_data_panel_wifi, 420, 38);
    lv_obj_set_style_radius(ui_data_panel_wifi, 6, LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_data_panel_wifi, lv_color_make(0, 5, 15), LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_data_panel_wifi, 1, LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_data_panel_wifi, lv_color_make(0, 229, 255), LV_STATE_DEFAULT);
    /* --- Widget: label_wifi (label) --- */
    ui_label_wifi = lv_label_create(ui_data_panel_wifi);
    lv_obj_set_pos(ui_label_wifi, 12, 8);
    lv_obj_set_size(ui_label_wifi, 60, 22);
    lv_obj_set_style_text_color(ui_label_wifi, lv_color_hex(0x00E5FF), LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_wifi, &tech_14, LV_STATE_DEFAULT);
    lv_label_set_text(ui_label_wifi, "WIFI:");
    
    /* --- Widget: val_wifi (label) --- */
    ui_val_wifi = lv_label_create(ui_data_panel_wifi);
    lv_obj_set_pos(ui_val_wifi, 78, 8);
    lv_obj_set_size(ui_val_wifi, 330, 22);
    lv_obj_set_style_text_color(ui_val_wifi, lv_color_hex(0xFFFFFF), LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_val_wifi, &tech_14, LV_STATE_DEFAULT);
    lv_label_set_text(ui_val_wifi, "MedFlow_Office_5G (192.168.1.100)");
    
    
    /* --- Widget: data_panel_ble (panel) --- */
    ui_data_panel_ble = lv_obj_create(screen);
    lv_obj_set_pos(ui_data_panel_ble, 30, 394);
    lv_obj_set_size(ui_data_panel_ble, 420, 38);
    lv_obj_set_style_radius(ui_data_panel_ble, 6, LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_data_panel_ble, lv_color_make(0, 5, 15), LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_data_panel_ble, 1, LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_data_panel_ble, lv_color_make(41, 121, 255), LV_STATE_DEFAULT);
    /* --- Widget: label_ble (label) --- */
    ui_label_ble = lv_label_create(ui_data_panel_ble);
    lv_obj_set_pos(ui_label_ble, 12, 8);
    lv_obj_set_size(ui_label_ble, 46, 22);
    lv_obj_set_style_text_color(ui_label_ble, lv_color_hex(0x2979FF), LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_ble, &tech_14, LV_STATE_DEFAULT);
    lv_label_set_text(ui_label_ble, "BLE:");
    
    /* --- Widget: val_ble (label) --- */
    ui_val_ble = lv_label_create(ui_data_panel_ble);
    lv_obj_set_pos(ui_val_ble, 58, 8);
    lv_obj_set_size(ui_val_ble, 350, 22);
    lv_obj_set_style_text_color(ui_val_ble, lv_color_hex(0xFFFFFF), LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_val_ble, &tech_14, LV_STATE_DEFAULT);
    lv_label_set_text(ui_val_ble, "12 Devices Linked");
    
    
    /* --- Widget: trigger_btn (btn) --- */
    ui_trigger_btn = lv_btn_create(screen);
    lv_obj_set_pos(ui_trigger_btn, 120, 440);
    lv_obj_set_size(ui_trigger_btn, 240, 36);
    lv_obj_set_style_radius(ui_trigger_btn, 4, LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_trigger_btn, lv_color_make(0, 5, 15), LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_trigger_btn, 1, LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_trigger_btn, lv_color_hex(0x00E5FF), LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_trigger_btn, lv_color_hex(0x00E5FF), LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_trigger_btn, &tech_14, LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_trigger_btn, 2, LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_trigger_btn, lv_color_make(0, 229, 255), LV_STATE_HOVER);
    lv_label_set_text(ui_trigger_btn, "TRIGGER ERROR STATE");
    static void on_trigger_btn_on_click(lv_event_t *e) {
        extern void ui_apply_state(const char *state_name);
        ui_apply_state("error");
    }
    lv_obj_add_event_cb(ui_trigger_btn, on_trigger_btn_on_click, LV_EVENT_CLICKED, NULL);
    
    
    return screen;
}


/* ══════════════════════════════════════════════════════ */
/* UI State Machine                                         */
/* ══════════════════════════════════════════════════════ */

typedef enum {
    UI_STATE_ERROR = 0,
    UI_STATE_COUNT
} ui_state_t;

static ui_state_t ui_current_state = UI_STATE_DEFAULT;
static ui_state_t ui_previous_state = UI_STATE_DEFAULT;

static const char *ui_state_names[] = {
    "error",
};

void ui_apply_state(const char *state_name) {
    ui_previous_state = ui_current_state;
    
    /* Find state index */
    for (int i = 0; i < UI_STATE_COUNT; i++) {
        if (strcmp(ui_state_names[i], state_name) == 0) {
            ui_current_state = (ui_state_t)i;
            break;
        }
    }
    
    /* Apply state-specific overrides */
    switch (ui_current_state) {
        case UI_STATE_ERROR: {
            /* Switch image to error variant */
            lv_img_set_src(ui_center_icon, &img_center_icon_error);
            lv_obj_set_style_text_color(ui_label_wifi, lv_color_hex(0xFF9100), LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(ui_label_ble, lv_color_hex(0xFF9100), LV_STATE_DEFAULT);
            lv_label_set_text(ui_val_wifi, "OFFLINE (DHCP TIMEOUT)");
            lv_label_set_text(ui_val_ble, "DRIVER FAULT (CODE: 0x9F)");
            lv_obj_set_style_border_color(ui_data_panel_wifi, lv_color_make(255, 145, 0), LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(ui_data_panel_ble, lv_color_make(255, 145, 0), LV_STATE_DEFAULT);
            lv_obj_set_style_text_color(ui_trigger_btn, lv_color_hex(0xFF9100), LV_STATE_DEFAULT);
            lv_obj_set_style_border_color(ui_trigger_btn, lv_color_hex(0xFF9100), LV_STATE_DEFAULT);
            lv_label_set_text(ui_trigger_btn, "RESTORE SYSTEM");
            break;
        }
        default: break;
    }
}

void ui_toggle_state(const char *state_a, const char *state_b) {
    if (strcmp(ui_state_names[ui_current_state], state_a) == 0) {
        ui_apply_state(state_b);
    } else {
        ui_apply_state(state_a);
    }
}


/* ══════════════════════════════════════════════════════ */
/* Asset Manifest                                           */
/* ══════════════════════════════════════════════════════ */
/*
 * Image assets referenced by this UI. Convert them with:
 *   python assets_pipeline.py --input <files> --output data/
 */
/*
 *   - OneRing/hmi_bg_pro.png
 *   - OneRing/hmi_ble_ring_pro_trans.png
 *   - OneRing/hmi_icon_alert_pro_trans.png
 *   - OneRing/hmi_icon_router_pro_trans.png
 *   - OneRing/hmi_wifi_ring_pro_trans.png
 */
