/*
 * Copyright © 2020 NXP.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *
 * o Redistributions of source code must retain the above copyright notice, this list
 *   of conditions and the following disclaimer.
 *
 * o Redistributions in binary form must reproduce the above copyright notice, this
 *   list of conditions and the following disclaimer in the documentation and/or
 *   other materials provided with the distribution.
 *
 * o Neither the name of the copyright holder nor the names of its
 *   contributors may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
 
/**
* \version  V1.0
* \date     2020/09/18
*/

#ifndef __TJA1145AFD_configurations_h
#define __TJA1145AFD_configurations_h

#include "NXP_TJA1145AFD_Functions.h"
#include "NXP_TJA1145AFD_Sim.h"


/********** TJA1145A Normal Mode configuration ***********/

// System Event Enable in Normal Mode
TJA1145AFD_System_Event_Enable_Reg_t TJA1145AFD_SYS_EVENT_EN_NORMAL = {TJA1145AFD_OTWE_OVER_TEMPERATURE_WARNING_ENABLED, TJA1145AFD_SPIFE_SPI_FAILURE_DETECTION_ENABLED};   
// Transceiver Event Enable in Normal Mode
TJA1145AFD_Transceiver_Event_Enable_Reg_t TJA1145AFD_TRX_EVENT_EN_NORMAL = {TJA1145AFD_CBSE_CAN_BUS_SILENCE_DETECTION_DISABLED, TJA1145AFD_CFE_CAN_FAILURE_DETECTION_ENABLE, TJA1145AFD_CWE_CAN_WAKEUP_DETECTION_DISABLE};
// WAKE Pin Enable in Normal Mode
TJA1145AFD_Wake_Pin_Enable_Reg_t TJA1145AFD_WAKE_PIN_EN_NORMAL = {TJA1145AFD_WPRE_WAKEPIN_RISING_EDGE_DETECT_DISABLE, TJA1145AFD_WPFE_WAKEPIN_FALLING_EDGE_DETECT_DISABLE};


/********** TJA1145A Standby configuration ***********/

// System Event Enabled in Standby Mode
TJA1145AFD_System_Event_Enable_Reg_t TJA1145AFD_SYS_EVENT_EN_STANDBY = {TJA1145AFD_OTWE_OVER_TEMPERATURE_WARNING_ENABLED, TJA1145AFD_SPIFE_SPI_FAILURE_DETECTION_ENABLED};   
// Transceiver Event Enable in Standby Mode
TJA1145AFD_Transceiver_Event_Enable_Reg_t TJA1145AFD_TRX_EVENT_EN_STANDBY = {TJA1145AFD_CBSE_CAN_BUS_SILENCE_DETECTION_ENABLED, TJA1145AFD_CFE_CAN_FAILURE_DETECTION_DISABLE, TJA1145AFD_CWE_CAN_WAKEUP_DETECTION_ENABLE};
// WAKE Pin Enable in Standby Mode
TJA1145AFD_Wake_Pin_Enable_Reg_t TJA1145AFD_WAKE_PIN_EN_STANDBY = {TJA1145AFD_WPRE_WAKEPIN_RISING_EDGE_DETECT_DISABLE, TJA1145AFD_WPFE_WAKEPIN_FALLING_EDGE_DETECT_ENABLE};
// CAN PN Control in Standby Mode
TJA1145AFD_CAN_Selective_WakeUp_t TJA1145AFD_CPNC_STANDBY = TJA1145AFD_CPNC_CAN_SELECTIVE_WAKEUP_ENABLE;                                                             

/********** TJA1145A Sleep configuration ***********/

// System Event Enabled in Sleep Mode
TJA1145AFD_System_Event_Enable_Reg_t TJA1145AFD_SYS_EVENT_EN_SLEEP = {TJA1145AFD_OTWE_OVER_TEMPERATURE_WARNING_ENABLED, TJA1145AFD_SPIFE_SPI_FAILURE_DETECTION_ENABLED};
// Transceiver Event Enable in Sleep Mode
TJA1145AFD_Transceiver_Event_Enable_Reg_t TJA1145AFD_TRX_EVENT_EN_SLEEP = {TJA1145AFD_CBSE_CAN_BUS_SILENCE_DETECTION_DISABLED, TJA1145AFD_CFE_CAN_FAILURE_DETECTION_DISABLE, TJA1145AFD_CWE_CAN_WAKEUP_DETECTION_ENABLE};
// WAKE Pin Enable in Sleep Mode
TJA1145AFD_Wake_Pin_Enable_Reg_t TJA1145AFD_WAKE_PIN_EN_SLEEP = {TJA1145AFD_WPRE_WAKEPIN_RISING_EDGE_DETECT_ENABLE, TJA1145AFD_WPFE_WAKEPIN_FALLING_EDGE_DETECT_DISABLE};
// CAN PN Control in Sleep Mode
TJA1145AFD_CAN_Selective_WakeUp_t TJA1145AFD_CPNC_SLEEP = TJA1145AFD_CPNC_CAN_SELECTIVE_WAKEUP_ENABLE;  //SLEEP MODE ENABLE CPNC

/********** TJA1145A init configuration ***********/

// System Event Enable initialisation value
TJA1145AFD_System_Event_Enable_Reg_t TJA1145AFD_SYS_EVENT_EN_INIT = {TJA1145AFD_OTWE_OVER_TEMPERATURE_WARNING_ENABLED, TJA1145AFD_SPIFE_SPI_FAILURE_DETECTION_ENABLED};
// GPM initialisation value
TJA1145AFD_RAM_Memory_0700_t TJA1145AFD_GPM0_INIT = 0x0;
TJA1145AFD_RAM_Memory_0815_t TJA1145AFD_GPM1_INIT = 0x0;
TJA1145AFD_RAM_Memory_1623_t TJA1145AFD_GPM2_INIT = 0x0;
TJA1145AFD_RAM_Memory_1623_t TJA1145AFD_GPM3_INIT = 0x0; 

// CAN Control initialisation value
TJA1145AFD_CAN_Control_Reg_t TJA1145AFD_CAN_CONTROL_INIT = {
	TJA1145AFD_CFDC_CAN_FD_TOLERANCE_DISABLED, 
	TJA1145AFD_PNCOK_PARTIAL_NETWORK_CONFIGURATION_INVALID, 
	TJA1145AFD_CPNC_CAN_SELECTIVE_WAKEUP_DISABLE, 
	TJA1145AFD_CMC_ACTIVE_WITH_VCC_UNDERVOLTAGE_DETECTION_OFF
};        
// Transceiver Event Enable initialisation value
TJA1145AFD_Transceiver_Event_Enable_Reg_t TJA1145AFD_TRX_EVENT_EN_INIT = {TJA1145AFD_CBSE_CAN_BUS_SILENCE_DETECTION_DISABLED, TJA1145AFD_CFE_CAN_FAILURE_DETECTION_DISABLE, TJA1145AFD_CWE_CAN_WAKEUP_DETECTION_DISABLE};

// Partial Networking Configuration
TJA1145AFD_CAN_Data_Rate_t TJA1145AFD_CAN_DATA_RATE = TJA1145AFD_CDR_500_KBIT_PER_S;	//26
Word UJA116FDVX_CAN_ID = 0x000;
Word TJA1145AFD_CAN_ID_MASK = 0x00F;
TJA1145AFD_Frame_Control_Reg_t TJA1145AFD_CAN_FRAME_CONTROL = {TJA1145AFD_IDE_STANDARD_FRAME_FORMAT_11_BIT, TJA1145AFD_PNDM_DATA_LENGTH_CODE_AND_DATA_FIELD_ARE_EVALUATED_AT_WAKE_UP, TJA1145AFD_DLC_EXPECTED_CAN_FRAME_BYTES_8};	//2F
TJA1145AFD_Data_Mask_0_Config_t TJA1145AFD_CAN_DATA_MASK0 = 0x00;	//68// 1st byte on the bus; if DLC = 1, last byte on the bus 
TJA1145AFD_Data_Mask_1_Config_t TJA1145AFD_CAN_DATA_MASK1 = 0x00;	//69// 2nd byte on the bus; if DLC = 2, last byte on the bus 
TJA1145AFD_Data_Mask_2_Config_t TJA1145AFD_CAN_DATA_MASK2 = 0x00;	//6A	// 3rd byte on the bus; if DLC = 3, last byte on the bus
TJA1145AFD_Data_Mask_3_Config_t TJA1145AFD_CAN_DATA_MASK3 = 0x00;	//6B	// 4th byte on the bus; if DLC = 4, last byte on the bus
TJA1145AFD_Data_Mask_4_Config_t TJA1145AFD_CAN_DATA_MASK4 = 0x09;	//6C	// 5th byte on the bus; if DLC = 5, last byte on the bus
TJA1145AFD_Data_Mask_5_Config_t TJA1145AFD_CAN_DATA_MASK5 = 0x00;	//6D	// 6th byte on the bus; if DLC = 6, last byte on the bus
TJA1145AFD_Data_Mask_6_Config_t TJA1145AFD_CAN_DATA_MASK6 = 0x00;	//6E	// 7th byte on the bus; if DLC = 7, last byte on the bus
TJA1145AFD_Data_Mask_7_Config_t TJA1145AFD_CAN_DATA_MASK7 = 0x09;	//6F	// 8th byte on the bus; if DLC = 8, last byte on the bus

// WAKE Pin Enable initialisation value
TJA1145AFD_Wake_Pin_Enable_Reg_t TJA1145AFD_WAKE_PIN_INIT = {TJA1145AFD_WPRE_WAKEPIN_RISING_EDGE_DETECT_DISABLE, TJA1145AFD_WPFE_WAKEPIN_FALLING_EDGE_DETECT_DISABLE};


#endif