/*
 * ui_screen.c — Gateway HMI Dual-Ring Screen
 * Auto-generated by json2lvgl.py, hand-tuned for GW202601_LVGL
 * Targets IT9866 with IT2D GPU acceleration
 */

#include <lvgl.h>
#include <string.h>
#include "ui_screen.h"

/* Asset declarations — generated by assets_pipeline.py in data/ */
LV_IMG_DECLARE(img_hmi_bg_pro);
LV_IMG_DECLARE(img_hmi_wifi_ring_pro_trans);
LV_IMG_DECLARE(img_hmi_ble_ring_pro_trans);
LV_IMG_DECLARE(img_hmi_icon_router_pro_trans);
LV_IMG_DECLARE(img_hmi_icon_alert_pro_trans);

/* Widget instances */
lv_obj_t *ui_wifi_ring;
lv_obj_t *ui_ble_ring;
lv_obj_t *ui_center_icon;
lv_obj_t *ui_data_panel_wifi;
lv_obj_t *ui_label_wifi;
lv_obj_t *ui_val_wifi;
lv_obj_t *ui_data_panel_ble;
lv_obj_t *ui_label_ble;
lv_obj_t *ui_val_ble;
lv_obj_t *ui_trigger_btn;

/* State tracking */
static int ui_is_error = 0;

/* Forward declaration */
static void on_trigger_btn_click(lv_event_t *e);

/* ══════════════════════════════════════════════════════ */
/* Screen Creation                                         */
/* ══════════════════════════════════════════════════════ */

lv_obj_t *ui_screen_create(void)
{
    lv_obj_t *screen = lv_obj_create(NULL);
    lv_obj_set_size(screen, 480, 480);
    lv_obj_set_style_bg_color(screen, lv_color_hex(0x050A10), LV_STATE_DEFAULT);

    /* Background image (480x480) */
    lv_obj_t *bg = lv_img_create(screen);
    lv_img_set_src(bg, &img_hmi_bg_pro);
    lv_obj_set_pos(bg, 0, 0);

    /* ── WiFi Ring (outer, cyan glow) ── */
    ui_wifi_ring = lv_img_create(screen);
    lv_img_set_src(ui_wifi_ring, &img_hmi_wifi_ring_pro_trans);
    lv_obj_set_pos(ui_wifi_ring, 24, 24);
    lv_obj_set_size(ui_wifi_ring, 432, 432);

    /* WiFi ring rotation animation */
    lv_anim_t anim_wifi;
    lv_anim_init(&anim_wifi);
    lv_anim_set_var(&anim_wifi, ui_wifi_ring);
    lv_anim_set_exec_cb(&anim_wifi, (lv_anim_exec_xcb_t)lv_img_set_angle);
    lv_anim_set_values(&anim_wifi, 0, 3600);
    lv_anim_set_time(&anim_wifi, 40000);
    lv_anim_set_repeat_count(&anim_wifi, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_path_cb(&anim_wifi, lv_anim_path_linear);
    lv_anim_start(&anim_wifi);

    /* ── BLE Ring (inner, blue glow, reverse rotation) ── */
    ui_ble_ring = lv_img_create(screen);
    lv_img_set_src(ui_ble_ring, &img_hmi_ble_ring_pro_trans);
    lv_obj_set_pos(ui_ble_ring, 72, 72);
    lv_obj_set_size(ui_ble_ring, 336, 336);

    lv_anim_t anim_ble;
    lv_anim_init(&anim_ble);
    lv_anim_set_var(&anim_ble, ui_ble_ring);
    lv_anim_set_exec_cb(&anim_ble, (lv_anim_exec_xcb_t)lv_img_set_angle);
    lv_anim_set_values(&anim_ble, 3600, 0);
    lv_anim_set_time(&anim_ble, 30000);
    lv_anim_set_repeat_count(&anim_ble, LV_ANIM_REPEAT_INFINITE);
    lv_anim_set_path_cb(&anim_ble, lv_anim_path_linear);
    lv_anim_start(&anim_ble);

    /* ── Center Icon (router / alert) ── */
    ui_center_icon = lv_img_create(screen);
    lv_img_set_src(ui_center_icon, &img_hmi_icon_router_pro_trans);
    lv_obj_set_pos(ui_center_icon, 180, 180);
    lv_obj_set_size(ui_center_icon, 120, 120);

    /* ── Data Panel: WiFi ── */
    ui_data_panel_wifi = lv_obj_create(screen);
    lv_obj_set_pos(ui_data_panel_wifi, 30, 348);
    lv_obj_set_size(ui_data_panel_wifi, 420, 38);
    lv_obj_set_style_radius(ui_data_panel_wifi, 6, LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_data_panel_wifi, lv_color_make(0, 5, 15), LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_data_panel_wifi, 191, LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_data_panel_wifi, 1, LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_data_panel_wifi, lv_color_make(0, 229, 255), LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_data_panel_wifi, 64, LV_STATE_DEFAULT);

    ui_label_wifi = lv_label_create(ui_data_panel_wifi);
    lv_obj_set_pos(ui_label_wifi, 12, 8);
    lv_label_set_text(ui_label_wifi, "WIFI:");
    lv_obj_set_style_text_color(ui_label_wifi, lv_color_hex(0x00E5FF), LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_wifi, &lv_font_montserrat_14, LV_STATE_DEFAULT);

    ui_val_wifi = lv_label_create(ui_data_panel_wifi);
    lv_obj_set_pos(ui_val_wifi, 78, 8);
    lv_label_set_text(ui_val_wifi, "MedFlow_Office_5G (192.168.1.100)");
    lv_obj_set_style_text_color(ui_val_wifi, lv_color_hex(0xFFFFFF), LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_val_wifi, &lv_font_montserrat_14, LV_STATE_DEFAULT);

    /* ── Data Panel: BLE ── */
    ui_data_panel_ble = lv_obj_create(screen);
    lv_obj_set_pos(ui_data_panel_ble, 30, 394);
    lv_obj_set_size(ui_data_panel_ble, 420, 38);
    lv_obj_set_style_radius(ui_data_panel_ble, 6, LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_data_panel_ble, lv_color_make(0, 5, 15), LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_data_panel_ble, 191, LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_data_panel_ble, 1, LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_data_panel_ble, lv_color_make(41, 121, 255), LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_data_panel_ble, 64, LV_STATE_DEFAULT);

    ui_label_ble = lv_label_create(ui_data_panel_ble);
    lv_obj_set_pos(ui_label_ble, 12, 8);
    lv_label_set_text(ui_label_ble, "BLE:");
    lv_obj_set_style_text_color(ui_label_ble, lv_color_hex(0x2979FF), LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_label_ble, &lv_font_montserrat_14, LV_STATE_DEFAULT);

    ui_val_ble = lv_label_create(ui_data_panel_ble);
    lv_obj_set_pos(ui_val_ble, 58, 8);
    lv_label_set_text(ui_val_ble, "12 Devices Linked");
    lv_obj_set_style_text_color(ui_val_ble, lv_color_hex(0xFFFFFF), LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_val_ble, &lv_font_montserrat_14, LV_STATE_DEFAULT);

    /* ── Error Trigger Button ── */
    ui_trigger_btn = lv_btn_create(screen);
    lv_obj_set_pos(ui_trigger_btn, 120, 440);
    lv_obj_set_size(ui_trigger_btn, 240, 36);
    lv_obj_set_style_radius(ui_trigger_btn, 4, LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_trigger_btn, lv_color_make(0, 5, 15), LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_trigger_btn, 204, LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_trigger_btn, 1, LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_trigger_btn, lv_color_hex(0x00E5FF), LV_STATE_DEFAULT);

    lv_obj_t *btn_label = lv_label_create(ui_trigger_btn);
    lv_label_set_text(btn_label, "TRIGGER ERROR STATE");
    lv_obj_set_style_text_color(btn_label, lv_color_hex(0x00E5FF), LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(btn_label, &lv_font_montserrat_14, LV_STATE_DEFAULT);
    lv_obj_center(btn_label);

    lv_obj_add_event_cb(ui_trigger_btn, on_trigger_btn_click, LV_EVENT_CLICKED, NULL);

    /* Load screen */
    lv_scr_load(screen);
    return screen;
}

/* ══════════════════════════════════════════════════════ */
/* State Machine                                           */
/* ══════════════════════════════════════════════════════ */

void ui_apply_state(const char *state_name)
{
    if (strcmp(state_name, "error") == 0) {
        ui_is_error = 1;

        /* Switch center icon to alert */
        lv_img_set_src(ui_center_icon, &img_hmi_icon_alert_pro_trans);

        /* Change WiFi panel border + label to orange */
        lv_obj_set_style_text_color(ui_label_wifi, lv_color_hex(0xFF9100), LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ui_data_panel_wifi, lv_color_make(255, 145, 0), LV_STATE_DEFAULT);

        /* Change BLE panel border + label to orange */
        lv_obj_set_style_text_color(ui_label_ble, lv_color_hex(0xFF9100), LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ui_data_panel_ble, lv_color_make(255, 145, 0), LV_STATE_DEFAULT);

        /* Update text values */
        lv_label_set_text(ui_val_wifi, "OFFLINE (DHCP TIMEOUT)");
        lv_label_set_text(ui_val_ble, "DRIVER FAULT (CODE: 0x9F)");

        /* Update button */
        lv_obj_set_style_border_color(ui_trigger_btn, lv_color_hex(0xFF9100), LV_STATE_DEFAULT);
        lv_obj_t *btn_lbl = lv_obj_get_child(ui_trigger_btn, 0);
        if (btn_lbl) {
            lv_label_set_text(btn_lbl, "RESTORE SYSTEM");
            lv_obj_set_style_text_color(btn_lbl, lv_color_hex(0xFF9100), LV_STATE_DEFAULT);
        }

    } else {
        ui_is_error = 0;

        /* Restore center icon */
        lv_img_set_src(ui_center_icon, &img_hmi_icon_router_pro_trans);

        /* Restore WiFi panel */
        lv_obj_set_style_text_color(ui_label_wifi, lv_color_hex(0x00E5FF), LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ui_data_panel_wifi, lv_color_make(0, 229, 255), LV_STATE_DEFAULT);

        /* Restore BLE panel */
        lv_obj_set_style_text_color(ui_label_ble, lv_color_hex(0x2979FF), LV_STATE_DEFAULT);
        lv_obj_set_style_border_color(ui_data_panel_ble, lv_color_make(41, 121, 255), LV_STATE_DEFAULT);

        /* Restore text values */
        lv_label_set_text(ui_val_wifi, "MedFlow_Office_5G (192.168.1.100)");
        lv_label_set_text(ui_val_ble, "12 Devices Linked");

        /* Restore button */
        lv_obj_set_style_border_color(ui_trigger_btn, lv_color_hex(0x00E5FF), LV_STATE_DEFAULT);
        lv_obj_t *btn_lbl = lv_obj_get_child(ui_trigger_btn, 0);
        if (btn_lbl) {
            lv_label_set_text(btn_lbl, "TRIGGER ERROR STATE");
            lv_obj_set_style_text_color(btn_lbl, lv_color_hex(0x00E5FF), LV_STATE_DEFAULT);
        }
    }
}

void ui_toggle_state(const char *state_a, const char *state_b)
{
    if (ui_is_error) {
        ui_apply_state(state_a);
    } else {
        ui_apply_state(state_b);
    }
}

/* ══════════════════════════════════════════════════════ */
/* Event Handlers                                          */
/* ══════════════════════════════════════════════════════ */

static void on_trigger_btn_click(lv_event_t *e)
{
    if (ui_is_error) {
        ui_apply_state("normal");
    } else {
        ui_apply_state("error");
    }
}
