/*
 * FreeRTOS Kernel V10.2.1
 * Copyright (C) 2019 Amazon.com, Inc. or its affiliates.  All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in
 * the Software without restriction, including without limitation the rights to
 * use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do so,
 * subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * http://www.FreeRTOS.org
 * http://aws.amazon.com/freertos
 *
 * 1 tab == 4 spaces!
 */

/* FreeRTOS includes. */
#include "FreeRTOS.h"
#include "task.h"
#include "ite/ith.h"
#include <cpu_mtimer.h>

extern uint64_t ullNextTime;
extern const size_t uxTimerIncrementsForOneTick;

#if( configUSE_TICKLESS_IDLE == 1 )
/* Flag set from the timer interrupt to allow the sleep processing to know if
sleep mode was exited because of a tick interrupt, or an interrupt
generated by something else. */
static volatile BaseType_t xTickFlag = pdFALSE;
#endif /* configUSE_TICKLESS_IDLE */

/*-----------------------------------------------------------*/

/*
 * Handler for timer interrupt
 */
void vPortSysTickHandler( void );

/*
 * Set the next interval for the timer
 */
static void prvSetNextTimerInterrupt( void );

/*-----------------------------------------------------------*/

#if( configUSE_TICKLESS_IDLE == 1 )

void vPortSuppressTicksAndSleep( TickType_t xExpectedIdleTime )
{
    /* The maximum number of tick periods that can be suppressed is limited by
    the resolution of the Timer */
    #define portULL_MAXIMUM_POSSIBLE_SUPPRESSED_TICKS ( (1ULL << 60) / uxTimerIncrementsForOneTick )

    /* Unit: cycle */
    uint64_t ullNextTickTime, ullWakeUpTime, ullCurrentTime;

    /* Unit: tick */
    TickType_t xCompleteTickPeriods, xTickPeriodsBeforeWakeup, xModifiableIdleTime;

    /* To avoid integer overflow when assigning maximum tick periods
    to xExpectedIdleTime, check portMAX_DELAY first.
    p.s. xExpectedIdleTime is always lower than portMAX_DELAY */
    if( portMAX_DELAY > portULL_MAXIMUM_POSSIBLE_SUPPRESSED_TICKS )
    {
        /* if portMAX_DELAY > portULL_MAXIMUM_POSSIBLE_SUPPRESSED_TICKS, then the
        size of TickType_t is larger than or equal to maximum tick periods */
        if( xExpectedIdleTime > portULL_MAXIMUM_POSSIBLE_SUPPRESSED_TICKS )
        {
            xExpectedIdleTime = (TickType_t) portULL_MAXIMUM_POSSIBLE_SUPPRESSED_TICKS;
        }
    }

    /* Stop mtime interrupt */
    ullNextTickTime = cpu_stop_mtime_irq();

    /* Calculate the mtimecmp value to wait xExpectedIdleTime tick periods.
    Wakeup time is at ( xExpectedIdleTime - 1 ) ticks after next tick. */
    ullWakeUpTime = ullNextTickTime + ( ( xExpectedIdleTime - 1 ) * (uint64_t)uxTimerIncrementsForOneTick );

    CPU_LOCAL_IRQ_DISABLE();
    if( eTaskConfirmSleepModeStatus() == eAbortSleep )
    {
        /* Set reload value and restart timer */
        cpu_set_mtimecmp( ullNextTickTime );

        /* Re-enable interrupts. */
        CPU_LOCAL_IRQ_ENABLE();
    }
    else
    {
        /* The tick flag is set to false before sleeping. If it is true when
        sleep mode is exited then sleep mode was probably exited because the
        tick was suppressed for the entire xExpectedIdleTime period. */
        xTickFlag = pdFALSE;

        /* Set wakeup time and restart timer. Also prepare next mtimecmp value 
        for Timer ISR. */
        cpu_set_mtimecmp( ullWakeUpTime );
        ullNextTime = ullWakeUpTime + uxTimerIncrementsForOneTick;

        /* Sleep until something happens.  configPRE_SLEEP_PROCESSING() can
        set its parameter to 0 to indicate that its implementation contains
        its own wait for interrupt or wait for event instruction, and so wfi
        should not be executed again.  However, the original expected idle
        time variable must remain unmodified, so a copy is taken. */
        xModifiableIdleTime = xExpectedIdleTime;
        configPRE_SLEEP_PROCESSING( xModifiableIdleTime );
        if( xModifiableIdleTime > 0 )
        {
            __asm volatile( "wfi" );
        }
        configPOST_SLEEP_PROCESSING( xExpectedIdleTime );

        /* Re-enable interrupts to allow the interrupt that brought the MCU
        out of sleep mode to execute immediately. */
        CPU_LOCAL_IRQ_ENABLE();

        /* Disable interrupts again to avoid timer ISR runs after checking
        xTickFlag. */
        CPU_LOCAL_IRQ_DISABLE();

        if( xTickFlag == pdTRUE )
        {
            /* As the pending tick will be processed as soon as this
            function exits, the tick value maintained by the tick is stepped
            forward by one less than the time spent waiting. */
            xCompleteTickPeriods = xExpectedIdleTime - 1;

            /* Note: mtimecmp is correct in this condition, so we doesn't
            need to access it */
        }
        else
        {
            ullCurrentTime = cpu_get_mtime();

            if( ullCurrentTime >= ullWakeUpTime )
            {
                /* Tick interrupt is pending because it occurs after
                disabling MIE. The tick value is stepped forward by
                the time spent waiting. */
                xCompleteTickPeriods = xExpectedIdleTime;
            }
            else
            {
                /* Something other than the tick interrupt ended the sleep.
                Work out how long the sleep lasted rounded to complete tick
                periods. */

                /* Round up the tick period before wakeup to the Tick unit */
                xTickPeriodsBeforeWakeup = ( ullWakeUpTime - ullCurrentTime - 1 ) / uxTimerIncrementsForOneTick + 1;
                xCompleteTickPeriods = xExpectedIdleTime - xTickPeriodsBeforeWakeup;
            }

            ullNextTime = ullNextTickTime + ( ( ( uint64_t ) xCompleteTickPeriods ) * uxTimerIncrementsForOneTick );
            cpu_set_mtimecmp( ullNextTime );

            /* Prepare next mtimecmp value for Timer ISR. */
            ullNextTime += ( uint64_t ) uxTimerIncrementsForOneTick;
        }

        vTaskStepTick( xCompleteTickPeriods );

        /* Exit with interrpts enabled. */
        CPU_LOCAL_IRQ_ENABLE();
    }
}
#endif /* configUSE_TICKLESS_IDLE */
/*-----------------------------------------------------------*/

/*
 * Create implementation of vPortSetupTimerInterrupt() if the CLINT is not
 * available, but make sure the configCLINT_BASE_ADDRESS constant is still
 * defined.
 */
void vPortSetupTimerInterrupt(void)
{
    ullNextTime = cpu_get_mtime();
    ullNextTime += ( uint64_t ) uxTimerIncrementsForOneTick;
    cpu_set_mtimecmp(ullNextTime);

    /* Prepare the time to use after the next tick interrupt. */
    ullNextTime += ( uint64_t ) uxTimerIncrementsForOneTick;
    
    /* Enable mtime interrupt */
    __asm volatile("csrs mie,%0"::"r"(0x80));
}
/*-----------------------------------------------------------*/

void freertos_tick_handler( void )
{
    /* Update the mtimer compare match value. */
    cpu_set_mtimecmp(ullNextTime);

    /* Add ullNextTime to the timer increments for one tick. */
    ullNextTime += ( uint64_t ) uxTimerIncrementsForOneTick;

    if( xTaskIncrementTick() != pdFALSE )
    {
        vTaskSwitchContext();
    }

#if( configUSE_TICKLESS_IDLE == 1 )
    xTickFlag = pdTRUE;
#endif /* configUSE_TICKLESS_IDLE */
}
/*-----------------------------------------------------------*/
