#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_USE_STDLIB_MALLOC        LV_STDLIB_CLIB
#define LV_USE_STDLIB_STRING        LV_STDLIB_CLIB
#define LV_USE_STDLIB_SPRINTF       LV_STDLIB_CLIB

#define LV_ATTRIBUTE_MEM_ALIGN __attribute__((aligned(4)))

#define LV_COLOR_DEPTH (CFG_LCD_BPP * 8)
#define LV_DEF_REFR_PERIOD 17
#define LV_CACHE_DEF_SIZE 1048576
#define LV_IMAGE_HEADER_CACHE_DEF_CNT 8

#define LV_USE_DRAW_ITE_IT2D 1
#define LV_ITE_IT2D_CACHE_SIZE (1024 * 1024 * 8)
#define LV_ITE_IT2D_LRU_SIZE (1024 * 1024 * 4)

#ifdef CFG_ENABLE_ROTATE
    #define LV_USE_ROTATE_ITE_IT2D 1
#endif

#define LV_USE_LOG 1
//#define LV_LOG_LEVEL LV_LOG_LEVEL_INFO
#define LV_LOG_PRINTF 1

#define LV_USE_SYSMON 1
#define LV_USE_PERF_MONITOR 1

#define LV_FONT_MONTSERRAT_12 1
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_16 1
#define LV_FONT_MONTSERRAT_18 1
#define LV_FONT_MONTSERRAT_20 1
#define LV_FONT_MONTSERRAT_22 1
#define LV_FONT_MONTSERRAT_24 1
#define LV_FONT_MONTSERRAT_26 1
#define LV_USE_FONT_COMPRESSED 1
#define LV_USE_BIDI 1
#define LV_USE_ARABIC_PERSIAN_CHARS 1
#define LV_FONT_DEJAVU_16_PERSIAN_HEBREW 1
#define LV_USE_FS_STDIO 1
#define LV_FS_STDIO_LETTER 'A'
#define LV_USE_LODEPNG 1
#define LV_USE_TJPGD 1
#define LV_USE_GIF 1
#define LV_USE_FREETYPE 1
#define LV_USE_RLOTTIE 1
#define LV_USE_SNAPSHOT 1
#define LV_USE_FLOAT 1
#define LV_USE_MATRIX 1
#define LV_USE_VECTOR_GRAPHIC 1
#define LV_USE_THORVG_INTERNAL 1
#define LV_USE_SVG 1
#define LV_USE_LOTTIE 1
#define LV_USE_DRAW_SW_COMPLEX_GRADIENTS 1
#define LV_USE_XML 1

#if defined(CFG_DPU_ENABLE) && defined(CFG_DCPS_ENABLE)
#define LV_USE_ITG 1
#endif

#ifdef CFG_VIDEO_ENABLE
#define LV_USE_FFMPEG 1
#if LV_USE_FFMPEG
    /*Dump input information to stderr*/
    #define LV_FFMPEG_AV_DUMP_FORMAT 1
#endif
#endif

#define LV_USE_DEMO_WIDGETS 1
#define LV_USE_DEMO_KEYPAD_AND_ENCODER 1
#define LV_USE_DEMO_BENCHMARK 1
#define LV_USE_DEMO_STRESS 1
#define LV_USE_DEMO_MUSIC 1
#define LV_DEMO_MUSIC_LANDSCAPE 1
#define LV_USE_DEMO_RENDER 1
#define LV_USE_DEMO_VECTOR_GRAPHIC 1

#define LV_BUILD_EXAMPLES 1

#define LV_CONF_SUPPRESS_DEFINE_CHECK 1

#endif /*LV_CONF_H*/
