#ifndef __UDS_STACK_ERR_H_
#define __UDS_STACK_ERR_H_

#define E_SUCCESS                                       (0)
#define S_OK                       						(0)
#define S_RECV_RESP_OK             						(0)
#define RESP_RECV_OK                                    (0)
#define E_FAILURE                                       (-1)
/*
 * Message Queue Related Error
 */
#define MQ_ERROR                                        (0xB0)
#define MQ_ERROR_BASE                                   (MQ_ERROR * E_FAILURE)
#define MQ_OPEN_ERR                                     (MQ_ERROR_BASE + 1)
#define MQ_UNLINK_ERR                                   (MQ_ERROR_BASE + 2)
#define MQ_SEND_ERR                                     (MQ_ERROR_BASE + 3)
#define MQ_WRITE_ERR                                    (MQ_ERROR_BASE + 4)
#define MQ_RECEIVE_ERR                                  (MQ_ERROR_BASE + 5)

/*
 * C Library Function Errors
 */
#define LIB_API_ERROR					(0xD0)
#define LIB_API_ERROR_BASE				(LIB_API_ERROR * E_FAILURE)
#define PTHREAD_CREATE_ERR				(LIB_API_ERROR_BASE + 1)	
#define SOCKET_CREATE_ERR				(LIB_API_ERROR_BASE + 2)
#define SET_SOCKOPT_ERR					(LIB_API_ERROR_BASE + 3)
#define SOCKET_BIND_ERR					(LIB_API_ERROR_BASE + 4)
#define SOCKET_CLOSE_ERR				(LIB_API_ERROR_BASE + 5)
#define SEM_INIT_ERR					(LIB_API_ERROR_BASE + 6)
#define FILE_OPEN_ERR					(LIB_API_ERROR_BASE + 7)
#define FILE_READ_ERR					(LIB_API_ERROR_BASE + 8)
#define MEMSET_ERR						(LIB_API_ERROR_BASE + 9)
#define STRCPY_ERR						(LIB_API_ERROR_BASE + 10)
#define SPRINTF_ERR						(LIB_API_ERROR_BASE + 11)
#define FCLOSE_ERR						(LIB_API_ERROR_BASE + 12)
#define CAN_BUS_BUSY					(LIB_API_ERROR_BASE + 13)
#define CAN_REQ_FAILED					(LIB_API_ERROR_BASE + 14)
#define CAN_RESP_FAILED					(LIB_API_ERROR_BASE + 15)
#define RESP_NOT_AVAILABLE              (LIB_API_ERROR_BASE + 16)
#define S_NOK                      		(LIB_API_ERROR_BASE + 17)
#define S_WAIT                     		(LIB_API_ERROR_BASE + 18)
#define S_RE_REQUEST               		(LIB_API_ERROR_BASE + 19)
#define S_REQUEST_WAIT             		(LIB_API_ERROR_BASE + 20)
#define REQUEST_COUNT_ERROR				(LIB_API_ERROR_BASE + 21)
/*
 * UDS Stack Libarary Errors
 */
#define E_UDS_STACK_ERR		        		(0xF0)
#define E_UDS_STACK_ERR_BASE				(E_UDS_STACK_ERR * E_FAILURE)
#define E_UDS_STACK_CAN_INIT_ERR			(E_UDS_STACK_ERR_BASE + 1)
#define E_UDS_STACK_NEGATIVE_CODE_ERR		(E_UDS_STACK_ERR_BASE + 2)
#define E_UDS_STACK_CAN_DEINIT_ERR			(E_UDS_STACK_ERR_BASE + 3)
#define E_UDS_STACK_GET_CLOCK_TIME_ERR		(E_UDS_STACK_ERR_BASE + 4)
#define E_UDS_STACK_RECV_TIMEOUT_ERR		(E_UDS_STACK_ERR_BASE + 5)
#define E_UDS_STACK_NO_RESPONSE				(E_UDS_STACK_ERR_BASE + 6)
#define E_UDS_STACK_INVALID_DATA			(E_UDS_STACK_ERR_BASE + 7)
#define E_CLUTCH_SWITCH_PEDAL_RELEASED		(E_UDS_STACK_ERR_BASE + 8)
#define E_CLUTCH_SWITCH_PEDAL_DEPRESSED		(E_UDS_STACK_ERR_BASE + 9)
#define E_BREAK_SWITCH_PEDAL_RELEASED		(E_UDS_STACK_ERR_BASE + 10)
#define E_BREAK_SWITCH_PEDAL_DEPRESSED		(E_UDS_STACK_ERR_BASE + 11)
#define E_CRUICE_CNTRL_OFF				    (E_UDS_STACK_ERR_BASE + 12)
#define E_CRUICE_CNTRL_ON				    (E_UDS_STACK_ERR_BASE + 13)
#define E_PTO_DISABLED					    (E_UDS_STACK_ERR_BASE + 14)
#define E_PTO_ACTIVE					    (E_UDS_STACK_ERR_BASE + 15)
#define E_PTO_NOT_AVAILABLE				    (E_UDS_STACK_ERR_BASE + 16)
#define E_UDS_STACK_INVALID_PGN				(E_UDS_STACK_ERR_BASE + 17)
#define E_DRIVER_CARD_1_NOT_PRESENT			(E_UDS_STACK_ERR_BASE + 18)
#define E_DRIVER_CARD_2_NOT_PRESENT         (E_UDS_STACK_ERR_BASE + 19)
#define E_NO_DRIVER_CARDS_PRESENT			(E_UDS_STACK_ERR_BASE + 20)
#define E_DRIVER_CARD_1_PRESENT				(E_UDS_STACK_ERR_BASE + 21)
#define E_DRIVER_CARD_2_PRESENT				(E_UDS_STACK_ERR_BASE + 22)
#define E_DRIVER_1_IN_REST				    (E_UDS_STACK_ERR_BASE + 23)
#define E_DRIVER_1_WORK					    (E_UDS_STACK_ERR_BASE + 24)
#define E_DRIVER_1_DRIVE				    (E_UDS_STACK_ERR_BASE + 25)
#define E_DRIVER_1_AVAILABLE				(E_UDS_STACK_ERR_BASE + 26)
#define E_DRIVER_1_ERROR				    (E_UDS_STACK_ERR_BASE + 27)
#define E_DRIVER_1_NOT_AVAILABLE			(E_UDS_STACK_ERR_BASE + 28)
#define E_DRIVER_2_IN_REST                              (E_UDS_STACK_ERR_BASE + 29)
#define E_DRIVER_2_WORK                                 (E_UDS_STACK_ERR_BASE + 30)
#define E_DRIVER_2_DRIVE                                (E_UDS_STACK_ERR_BASE + 31)
#define E_DRIVER_2_AVAILABLE                            (E_UDS_STACK_ERR_BASE + 32)
#define E_DRIVER_2_ERROR                                (E_UDS_STACK_ERR_BASE + 33)
#define E_DRIVER_2_NOT_AVAILABLE                        (E_UDS_STACK_ERR_BASE + 34)
#define E_DRIVER_1_REL_STATE_NORMAL						(E_UDS_STACK_ERR_BASE + 35)
#define E_DRIVER_1_REL_STATE_15MINS_TO_4_HALF_HRS		(E_UDS_STACK_ERR_BASE + 36)			
#define E_DRIVER_1_REL_STATE_REACHED_4_HALF_HRS			(E_UDS_STACK_ERR_BASE + 37)
#define E_DRIVER_1_REL_STATE_15MINS_BEFORE_9HRS			(E_UDS_STACK_ERR_BASE + 38)
#define E_DRIVER_1_REL_STATE_REACHED_9HRS				(E_UDS_STACK_ERR_BASE + 39)
#define E_DRIVER_1_REL_STATE_15MINS_BEFORE_16HRS		(E_UDS_STACK_ERR_BASE + 40)
#define E_DRIVER_1_REL_STATE_REACHED_16HRS				(E_UDS_STACK_ERR_BASE + 41)
#define E_DRIVER_1_REL_STATE_ERR						(E_UDS_STACK_ERR_BASE + 42)
#define E_DRIVER_1_REL_STATE_NOT_AVAILABLE				(E_UDS_STACK_ERR_BASE + 43)
#define E_DRIVER_2_REL_STATE_NORMAL                     (E_UDS_STACK_ERR_BASE + 44)
#define E_DRIVER_2_REL_STATE_15MINS_TO_4_HALF_HRS       (E_UDS_STACK_ERR_BASE + 45)
#define E_DRIVER_2_REL_STATE_REACHED_4_HALF_HRS         (E_UDS_STACK_ERR_BASE + 46)
#define E_DRIVER_2_REL_STATE_15MINS_BEFORE_9HRS         (E_UDS_STACK_ERR_BASE + 47)
#define E_DRIVER_2_REL_STATE_REACHED_9HRS               (E_UDS_STACK_ERR_BASE + 48)
#define E_DRIVER_2_REL_STATE_15MINS_BEFORE_16HRS        (E_UDS_STACK_ERR_BASE + 49)
#define E_DRIVER_2_REL_STATE_REACHED_16HRS              (E_UDS_STACK_ERR_BASE + 50)
#define E_DRIVER_2_REL_STATE_ERR                        (E_UDS_STACK_ERR_BASE + 51)
#define E_DRIVER_2_REL_STATE_NOT_AVAILABLE              (E_UDS_STACK_ERR_BASE + 52)
#define E_INVALID_DATA									(E_UDS_STACK_ERR_BASE + 53)
/*
 * Sample DBC File Read and Parse Errors
 */
#define E_UDS_SAMPLE_DBC_ERR				(0xE0)
#define E_UDS_SAMPLE_DBC_ERR_BASE			(E_UDS_SAMPLE_DBC_ERR * E_FAILURE)
#define E_UDS_SAMPLE_DBC_NO_DATA_FOUND		(E_UDS_SAMPLE_DBC_ERR_BASE + 1)
#define E_UDS_SAMPLE_DBC_INVALID_DATA		(E_UDS_SAMPLE_DBC_ERR_BASE + 2)

#endif
